# Run upstream `safe-global/safe-infrastructure` (docker-compose) verbatim
# against a NixOS-managed Docker daemon. We pin the upstream source via the
# `safe-infrastructure` flake input; bump with `nix flake update`.
#
# Per-deploy values (RPC URL, branding, secrets) are injected via:
#   - /var/lib/safe-multisig/.env          (top-level docker-compose vars)
#   - /var/lib/safe-multisig/override.yml  (per-service env overrides)
#
# Both are regenerated on each rebuild by the safe-multisig-stack systemd
# unit below.
{
  config,
  lib,
  pkgs,
  safe-infrastructure,
  ...
}:
let
  cfg = config.safeMultisig;
  stateDir = "/var/lib/safe-multisig";
  envFile = "${stateDir}/.env";
  overrideFile = "${stateDir}/override.yml";

  # The chain whose RPC + id are wired into the upstream `txs` indexer
  # and baked into the wallet bundle. See `options.nix` `primaryChain`.
  primary = cfg.chains.${cfg.primaryChain};

  # Pinned image versions. Bumped here, applied on next rebuild.
  versions = {
    UI_VERSION = "v1.88.0";
    CGW_VERSION = "v1.108.0";
    CFG_VERSION = "v2.94.0";
    TXS_VERSION = "v6.3.0";
    EVENTS_VERSION = "v1.3.0";
  };

  # Compose override. `@SAFE_MULTISIG_*@` placeholders substituted at Nix
  # eval time; `''${...}` references resolved at compose runtime from
  # /var/lib/safe-multisig/.env (generated by the stack unit below).
  override = pkgs.writeText "safe-multisig-override.yml" (
    builtins.replaceStrings
      [ "@SAFE_MULTISIG_DOMAIN@" "@SAFE_MULTISIG_CHAIN_ID@" ]
      [ cfg.domain (toString primary.chainId) ]
      (builtins.readFile ./override.yml.tmpl)
  );
  # docker compose invocation used by every safe-multisig-stack systemd unit.
  # `--project-directory ${stateDir}` so upstream's relative bind mounts
  # (`./data/<svc>-db`, `./docker/nginx/nginx.conf`) resolve under our
  # writable /var/lib/safe-multisig/, with symlinks pointing back to the
  # read-only nix store for the static bits.
  composeExe = "${pkgs.docker-compose}/bin/docker-compose";
  composeArgs = lib.concatStringsSep " " [
    "--project-directory ${stateDir}"
    "-f ${stateDir}/docker-compose.yml"
    "-f ${overrideFile}"
    "--env-file ${envFile}"
    "--project-name safe-multisig"
  ];

  versionEnvLines = lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "${k}=${v}") versions);

  emptyIfNull = v: if v == null then "" else v;
in
{
  systemd.tmpfiles.rules = [
    "d ${stateDir} 0755 root root -"
    "d ${stateDir}/secrets 0700 root root -"
  ];

  # docker-compose CLI on the host so operators can poke at the running
  # stack (`docker compose ps`, etc.). The Docker daemon itself is
  # enabled by the top-level safe-multisig module.
  environment.systemPackages = [ pkgs.docker-compose ];

  # ── Stack lifecycle ─────────────────────────────────────────────────────
  systemd.services.safe-multisig-stack = {
    description = "Safe multisig stack via docker compose";
    wantedBy = [ "multi-user.target" ];
    requires = [ "docker.service" ];
    after = [
      "docker.service"
      "network-online.target"
    ];
    wants = [ "network-online.target" ];

    path = [
      pkgs.docker
      pkgs.docker-compose
      pkgs.openssl
      pkgs.coreutils
    ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "safe-multisig-stack-up" ''
        set -eu
        umask 077

        # Stage upstream's project tree under ${stateDir} so its relative
        # bind mounts (./data/<svc>-db, ./docker/nginx/nginx.conf,
        # container_env_files/<svc>.env) resolve to a writable directory
        # backed by the read-only nix store for static bits.
        mkdir -p ${stateDir}/data
        ln -sfn ${safe-infrastructure}/docker-compose.yml ${stateDir}/docker-compose.yml
        ln -sfn ${safe-infrastructure}/docker ${stateDir}/docker
        ln -sfn ${safe-infrastructure}/container_env_files ${stateDir}/container_env_files

        # Generate / reuse runtime secrets (idempotent).
        gen() {
          local f="${stateDir}/secrets/$1"
          [ -e "$f" ] || openssl rand -hex 32 > "$f"
          cat "$f"
        }
        DJANGO_SECRET=$(gen django_secret)
        CGW_AUTH_TOKEN=$(gen cgw_auth_token)
        POSTGRES_PASSWORD=$(gen postgres_password)
        DJANGO_SUPERUSER_PASSWORD=$(gen django_superuser_password)

        cat > ${envFile} <<EOF
        # Generated by NixOS. Edits will be overwritten on next rebuild.
        ${versionEnvLines}
        REVERSE_PROXY_PORT=127.0.0.1:8000
        RPC_NODE_URL=${primary.rpcUri}
        DJANGO_SECRET=$DJANGO_SECRET
        CGW_AUTH_TOKEN=$CGW_AUTH_TOKEN
        POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD
        PRICES_PROVIDER_API_KEY=${emptyIfNull cfg.cgw.pricesProvider.apiKey}
        PRICES_PROVIDER_API_BASE_URI=${emptyIfNull cfg.cgw.pricesProvider.apiBaseUri}
        PRICES_TTL_SECONDS=${toString cfg.cgw.pricesProvider.tokenPricesTtlSeconds}
        NATIVE_COINS_PRICES_TTL_SECONDS=${toString cfg.cgw.pricesProvider.nativeCoinPricesTtlSeconds}
        ZERION_API_KEY=${emptyIfNull cfg.cgw.zerion.apiKey}
        EOF
        chmod 600 ${envFile}

        ln -sfn ${override} ${overrideFile}

        ${composeExe} ${composeArgs} pull --quiet
        # `up -d` doesn't recreate downstream containers when their deps
        # (image / config) change. Tell compose to recreate any whose
        # config differs from running state; `--no-recreate` would be the
        # inverse.
        ${composeExe} ${composeArgs} up -d --remove-orphans --wait-timeout 300
      '';
      ExecStop = pkgs.writeShellScript "safe-multisig-stack-down" ''
        ${composeExe} ${composeArgs} down --remove-orphans
      '';
    };
  };

  # ── Chain + service registration ─────────────────────────────────────────
  # Seeds cfg-service via `docker exec safe-multisig-cfg-web-1 python
  # manage.py shell`. The public `/cfg/api/v1/chains/` endpoint is read-only
  # and 405s on POST. `update_or_create` makes the script idempotent so it
  # can run on every rebuild.
  #
  # `Service` rows must exist or `/v2/chains/{service_key}/` returns 404
  # (cfg-service does `get_object_or_404` on the service key), which
  # cascades into a 404 on the CGW chain list and breaks the UI.
  systemd.services.safe-multisig-chain-bootstrap =
    let
      bootstrapData = {
        inherit (cfg) services;
        chains = lib.mapAttrsToList (_name: c: {
          id = c.chainId;
          name = c.chainName;
          short_name = c.shortName;
          inherit (c) description;
          inherit (c) l2;
          is_testnet = c.isTestnet;
          zk = false;
          rpc_authentication = "NO_AUTHENTICATION";
          rpc_uri = c.rpcUri;
          public_rpc_authentication = "NO_AUTHENTICATION";
          public_rpc_uri = c.rpcUri;
          safe_apps_rpc_authentication = "NO_AUTHENTICATION";
          safe_apps_rpc_uri = c.rpcUri;
          block_explorer_uri_address_template = c.blockExplorerUriTemplate.address;
          block_explorer_uri_tx_hash_template = c.blockExplorerUriTemplate.txHash;
          block_explorer_uri_api_template = c.blockExplorerUriTemplate.api;
          currency_name = c.nativeCurrency.name;
          currency_symbol = c.nativeCurrency.symbol;
          currency_decimals = c.nativeCurrency.decimals;
          currency_logo_uri = c.nativeCurrency.logoUri;
          chain_logo_uri = c.chainLogoUri;
          transaction_service_uri = c.transactionService;
          theme_text_color = cfg.branding.theme.textColor;
          theme_background_color = cfg.branding.theme.backgroundColor;
        }) cfg.chains;
      };

      bootstrapPy = pkgs.writeText "safe-multisig-chain-bootstrap.py" ''
        import json
        from chains.models import Chain, Service

        data = json.loads(${builtins.toJSON (builtins.toJSON bootstrapData)})

        for key in data["services"]:
            _, created = Service.objects.update_or_create(
                key=key,
                defaults={"name": key, "description": f"{key} service"},
            )
            print(f"service {key}: {'created' if created else 'updated'}")

        for c in data["chains"]:
            cid = c.pop("id")
            chain, created = Chain.objects.update_or_create(id=cid, defaults=c)
            print(f"chain {cid} ({chain.name}): {'created' if created else 'updated'}")
      '';
    in
    {
      description = "Seed safe-multisig chains and services into safe-config-service";
      wantedBy = [ "multi-user.target" ];
      after = [ "safe-multisig-stack.service" ];
      requires = [ "safe-multisig-stack.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      path = [
        pkgs.docker
        pkgs.curl
        pkgs.coreutils
      ];
      script = ''
        set -euo pipefail

        # Wait for cfg-web to answer through the internal nginx (the same
        # hop CGW uses, so this also confirms cfg→cgw plumbing).
        for _ in $(seq 1 90); do
          curl --fail --silent http://127.0.0.1:8000/cfg/api/v1/about/ \
            >/dev/null 2>&1 && break
          sleep 2
        done

        # Pipe the seed script in via stdin → Django shell exec.
        docker exec -i -w /app/src safe-multisig-cfg-web-1 \
          python manage.py shell <${bootstrapPy}
      '';
    };
}
